title: CV | Constantine Tourtsakis
description:  My CV
url: https://konstantinostourtsakis.github.io/jekyll-cv/
baseurl: /jekyll-cv
theme_skin: red

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
