title: CV | Constantine Tourtsakis
description:  My CV
url: https://github.com/KonstantinosTourtsakis/jekyll-cv/tree/2019140
baseurl: ''
theme_skin: red

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
